# Generated by Django 4.0.3 on 2022-04-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0007_alter_product_options_alter_productgallery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
