# Generated by Django 4.0.3 on 2022-04-03 18:07

from django.db import migrations, models
import eshop_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0004_sitesetting_logo_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={},
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='about_us',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='copy_right',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='fax',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to=eshop_settings.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='mobile',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
