# Generated by Django 4.0.3 on 2022-04-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_contact', '0002_auto_20200819_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={},
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='is_read',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='text',
            field=models.TextField(),
        ),
    ]
