# Generated by Django 4.0.3 on 2022-04-03 18:07

from django.db import migrations, models
import eshop_sliders.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_sliders', '0002_auto_20200713_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={},
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=eshop_sliders.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='slider',
            name='link',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
